- name: adiciona o usuário root no grupo sudo
  user:
    name: 'root'
    groups: sudo
    append: yes

- name: adiciona o usuário {{ sudo_user }} no grupo sudo
  user:
    name: '{{ sudo_user }}'
    groups: sudo
    append: yes

- name: criando ficheiro /etc/sudoers
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers"
    backup: yes