- name: adicionar regras em {{directory_scripts}}/ufw-rules.sh
  lineinfile:
    dest: '{{directory_scripts}}/ufw-rules.sh'
    insertbefore: .*EndMyRules 
    line: ufw default allow FORWARD
  register: regras_firewall_kvm
- name: rodando o script {{directory_scripts}}/ufw-rules.sh
  expect:
    command: /bin/bash -c '{{directory_scripts}}/ufw-rules.sh'
    responses:
      (?i)Proceed with operation (y|n)?: "y"
  when: regras_firewall_kvm.changed