---

- name: adicionar regras em {{directory_scripts}}/ufw-rules.sh
  lineinfile:
    dest: '{{directory_scripts}}/ufw-rules.sh'
    insertafter: .*ufw logging on 
    line: |

      # allow FORWARD
      ufw default allow FORWARD
  register: regras_firewall_kvm

- name: rodando o script {{directory_scripts}}/ufw-rules.sh
  expect:
    command: /bin/bash -c '{{directory_scripts}}/ufw-rules.sh'
    responses:
      (?i)Proceed with operation (y|n)?: "y"
  when: regras_firewall_kvm.changed

- name: instalar pacotes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - qemu-kvm
    - virtinst
    - virt-manager
    - libguestfs-tools
  register: kvm_instalar_pacotes

- name: reiniciar servidor
  reboot:
  when: kvm_instalar_pacotes.changed

- name: adicionar usuário root no grupo libvirt
  user:
    name: root
    groups: libvirt
    append: yes

- name: adicionar usuário {{sudo_user}} no grupo libvirt
  user:
    name: '{{sudo_user}}'
    groups: libvirt
    append: yes

- name: adicionar módulo kvm_intel
  modprobe:
    name: kvm_intel
    state: present    