---

- hosts: hosts_servers
  become: true
  become_user: root
  gather_facts: no  
  vars_files:
  - group_vars/all
  - group_vars/hosts-servers
  roles:
    - admin-environment
    - apt-config
    - default-packages
    - network-interfaces-config
    - network-hostname-config
    - resolv-config
    - time-zone-config
    - ntp-update
    - ssh-config
    - sudo-config
    - ufw
    - kvm
    - vagrant   