---

- hosts: docker_grafana
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3 python3-apt)
      register: output
      changed_when: output.stdout != ""
    - setup: # aka gather_facts
  tasks:
    - name: atualizar todos os pacotes para a última versão
      apt:
        update_cache: yes
        upgrade: full
        force_apt_get: yes