---

- hosts: domain_controller_servers
  become: true
  become_user: root
  gather_facts: no  
  vars_files:
  - group_vars/all
  - group_vars/domain-controller-servers
  roles:
    - admin-environment
    - apt-config
    - default-packages
    - network-interfaces-default-config
    - resolv-config
    - time-zone-config
    - vagrant-admin-environment
    - ssh-config
    - sudo-config
    - ufw 
    - samba-domain-controller
