# playbook for domain-member-servers tier

- hosts: domain_member_servers
  become: true
  become_user: root
  gather_facts: no  
  vars_files:
  - group_vars/all
  - group_vars/domain-member-servers
  roles:
    - apt-config
    - default-packages
    - vagrant-admin-environment
    - ssh
    - sudo-config
    - ufw 
#   - nfs-client    
    - samba-domain-member
#   - clamav
    - consul
    - vault
    - terraform
    - pxe
