---

- hosts: docker01_server
  become: true
  become_user: root
  tasks:

    # - name: add new docker connection
    #   add_host:
    #     name: "grafana1"
    #     groups: "docker_container1"
    #     ansible_connection: docker
    #     ansible_ssh_user: "root"
    #     ansible_become_user: "root"
    #     ansible_become: "yes"
    #     remote_addr: "grafana"
    #     remote_user: "root"

    - name: adicionar conexão com o container grafana
      add_host:
        name: grafana
        groups: "docker_container"
        ansible_connection: docker
        ansible_user: root
      changed_when: false    

# setup the new machine using ansible instead of docker
- hosts: docker_container
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3 python3-apt)
      register: output
      changed_when: output.stdout != ""
    - setup: # aka gather_facts
  tasks:
    - name: atualiza todos os pacotes para a última versão
      apt:
        update_cache: yes
        upgrade: full
        force_apt_get: yes
    - name: create directory for ssh keys
      delegate_to: grafana
      file:
        path: "/teste"
        state: directory