---

# run an empty centos 7 container
- hosts: docker01_server
  become: true
  become_user: root
  tasks:

    - name: add new docker connection
      add_host:
        name: "grafana"
        groups: "docker_container"
        ansible_connection: docker
        ansible_ssh_user: "root"
        ansible_become_user: "root"
        ansible_become: "yes"
        ansible_docker_host: "grafana"
        ansible_docker_user: "root"
        remote_addr: "grafana"
        remote_user: "root"


# setup the new machine using ansible instead of docker
- hosts: docker_container
  become: true
  become_user: root
  gather_facts: no  
  tasks:

    - ping:

    - name: install vi
      yum:
        name: vi
        state: present


