---

- hosts: docker01_server
  become: true
  become_user: root
  gather_facts: yes
  ansible_connection: docker
  ansible_docker_host: "grafana"
  tasks:
    - ping:

# run an empty centos 7 container
- hosts: docker01_server

  tasks:

    - name: add new docker connection
      add_host:
        name: "grafana"
        groups: "docker_container"
        ansible_connection: docker
        ansible_ssh_user: "root"
        ansible_become_user: "root"
        ansible_become: "yes"


# setup the new machine using ansible instead of docker
- hosts: docker_container
  gather_facts: no  
  tasks:

    - ping:

    - name: install vi
      yum:
        name: vi
        state: present


