---

- hosts: hosts_servers
  become: true
  become_user: root
  gather_facts: no  
  vars_files:
  - group_vars/all
  - group_vars/hosts-servers
  roles:
    - apt-config
    - default-packages
    - network-interfaces-kvm-config
    - network-config
    - time-zone-config
    - ntp-update
    - ssh-config
    - sudo-config
    - ufw