---

- hosts: hosts_servers
  become: true
  become_user: root
  gather_facts: no  
  vars_files:
  - group_vars/all
  - group_vars/hosts-servers
  roles:
    - apt-sources-list
    - default-packages
    - network-interfaces-kvm
    - sudo
