# master playbook

---
# tasks file for ansible-codes
- name: Configuração para "servers" hosts
  hosts: [servers]
  become: true
  become_user: root
  gather_facts: no  
  vars:
    debian_codename: 'stretch'
    timezone: 'America/Sao_Paulo'    
    dns_domain_name: 'RTHOMAZ.LOCAL'
    domain_admin_user : 'rodrigo'
    domain_admin_password : 'b3b3xu!@#'
    workgroup_name: 'RTHOMAZ'
    sudo_user: 'rodrigo'
    docker_work_path: 'docker-projects'
    ntp_servers: 
      - {cname: 'pdc-server.rthomaz.local', prefer: 'prefer' }
#     - {cname: 'bdc-server.rthomaz.local', prefer: '' }  

- import_playbook: domain-member-servers.yml
- import_playbook: docker-servers.yml


#  roles:   
#     - admin-enviroment
#     - apt-sources-list
#     - default-packages
#     - ssh
#     - ufw 
#     - nfs-client    
#     - samba-domain-member
#     - sudo
# #   - clamav
#     - consul
#     - vault
#     - terraform
#     - pxe

#    - docker-ce
#    - docker-elasticsearch-fluentd-kibana
#    - docker-mongodb
##   - docker-my-sql
#    - docker-postgres
#    - docker-postgres-adminer
#    - docker-rabbitmq         
#    - docker-nuget-server
#    - docker-nextcloud