---

- name: cria o diretório /{{workgroup_name}}/{{docker_work_path}}/rabbitmq se ele não existir
  file:
    path: /{{workgroup_name}}/{{docker_work_path}}/rabbitmq
    state: directory
    owner: root
    group: root
    mode: +rwx        
    
- name: criando Dockerfile /{{workgroup_name}}/{{docker_work_path}}/rabbitmq/Dockerfile
  template:
    src: "Dockerfile.j2"
    dest: "/{{workgroup_name}}/{{docker_work_path}}/rabbitmq/Dockerfile"
    backup: yes
    mode: a+x
    owner: root
    group: root
    
- name: cria a imagem rthomaz/rabbitmq
  docker_image:
    name: rthomaz/rabbitmq
    build:
      path: /{{workgroup_name}}/{{docker_work_path}}/images
      dockerfile: /{{workgroup_name}}/{{docker_work_path}}/rabbitmq/Dockerfile
      pull: yes
    push: no
    source: build
    
- name: exclui o container {{docker_rabbitmq_container_name}}
  command: docker rm -f -v {{docker_rabbitmq_container_name}}
  ignore_errors: yes    
  
- name: cria o container {{docker_rabbitmq_container_name}}
  command: docker run -d 
    --hostname {{docker_rabbitmq_container_name}}
    --name {{docker_rabbitmq_container_name}}
    --log-driver={{docker_rabbitmq_log_driver}}
    {% for log_opt in log_opts %}
    --log-opt {{log_opt.name}}={{log_opt.value}}
    {% endfor %}
    --network {{docker_rabbitmq_network}}
    -e RABBITMQ_DEFAULT_USER={{docker_rabbitmq_default_user}} 
    -e RABBITMQ_DEFAULT_PASS={{docker_rabbitmq_default_pass}} 
    -p 1883:1883 
    -p 4369:4369 
    -p 5671:5671 
    -p 5672:5672 
    -p 15671:15671 
    -p 15672:15672 
    -p 15674:15674 
    -p 15675:15675 
    -p 25672:25672 
    -p 61613:61613 
    rthomaz/rabbitmq:latest
  vars:
    log_opts:
      - { name: 'fluentd-address', value: 'localhost:24224'}
      - { name: 'tag', value: 'efk.rabbitmq' }