---

- name: cria o diretório {{docker_rabbitmq_directory_path}} se ele não existir
  file:
    path: '{{docker_rabbitmq_directory_path}}'
    state: directory
    owner: '{{docker_rabbitmq_files_owner}}'
    group: '{{docker_rabbitmq_files_group}}'
    mode: '{{docker_rabbitmq_files_mode}}'
    
- name: criando Dockerfile {{docker_rabbitmq_directory_path}}/Dockerfile
  template:
    src: 'Dockerfile.j2'
    dest: '{{docker_rabbitmq_directory_path}}/Dockerfile'
    backup: yes    
    owner: '{{docker_rabbitmq_files_owner}}'
    group: '{{docker_rabbitmq_files_group}}'
    mode: '{{docker_rabbitmq_files_mode}}'
    
- name: cria a imagem {{docker_rabbitmq_image_name}} do release rabbitmq:{{docker_rabbitmq_release}}
  docker_image:
    name: '{{docker_rabbitmq_image_name}}'
    build:
      path: '{{docker_folder_images_path}}'
      dockerfile: '{{docker_rabbitmq_directory_path}}/Dockerfile'
      pull: yes
    push: no
    source: build
    
#- name: exclui o container {{docker_rabbitmq_container_name}}
#  command: docker rm -f -v {{docker_rabbitmq_container_name}}
#  ignore_errors: yes    

- name: exclui qualquer container baseado na imagem {{docker_rabbitmq_image_name}} 
  command: 'docker ps -a | awk '{ print $1,$2 }' | grep {{docker_rabbitmq_image_name}}:latest | awk '{print $1 }' | xargs -I {} docker rm -f {}'
  
- name: cria o container {{docker_rabbitmq_container_name}}
  command: docker run -d 
    --hostname {{docker_rabbitmq_container_name}}
    --name {{docker_rabbitmq_container_name}}
    --log-driver={{docker_rabbitmq_log_driver}}
    {% for log_opt in docker_rabbitmq_log_opts %}
    --log-opt {{log_opt.name}}={{log_opt.value}}
    {% endfor %}
    --network {{docker_rabbitmq_network}}
    -e RABBITMQ_DEFAULT_USER={{docker_rabbitmq_default_user}} 
    -e RABBITMQ_DEFAULT_PASS={{docker_rabbitmq_default_pass}} 
    -p 4369:4369 
    -p 5671:5671 
    -p 5672:5672     
    -p 25672:25672 
    {% for plugin in docker_rabbitmq_plugins %}
        {% if plugin == 'rabbitmq_management' %}
    -p 15671:15671 
    -p 15672:15672
        {% elif plugin == 'rabbitmq_mqtt' %}
    -p 1883:1883
        {% elif plugin == 'rabbitmq_web_mqtt' %}
    -p 15675:15675
        {% elif plugin == 'rabbitmq_stomp' %}
    -p 61613:61613
        {% elif plugin == 'rabbitmq_web_stomp' %}
    -p 15674:15674   
        {% endif %}         
    {% endfor %}
    {{docker_rabbitmq_image_name}}:latest

# default ports

# 4369  = ?
# 5671  = amqp ssl
# 5672  = amqp
# 25672 = clustering

# 15671 = http ssl
# 15672 = http (RabbitMQ Management)
# 1883  = mqtt
# 15675 = http/web-mqtt
# 61613 = stomp
# 15674 = http/web-stomp