---
    
- name: exclui qualquer container baseado na imagem {{docker_mongo_express_image_name}} 
  shell: docker ps -a | awk '{ print $1,$2 }' | grep {{docker_mongo_express_image_name}} | awk '{print $1 }' | xargs -I {} docker rm -f {}

- name: cria o container {{docker_mongo_express_container_name}}
  command: docker run 
    --restart=unless-stopped -d 
    --name {{docker_mongo_express_container_name}}
    --network {{docker_mongo_express_network}}
    --log-driver={{docker_mongo_express_log_driver}}
    --log-opt fluentd-address={{docker_mongo_express_log_address}}
    --log-opt tag={{docker_mongo_express_log_tag}}
    -p {{docker_mongo_express_port}}:8081 
    -e "ME_CONFIG_MONGODB_SERVER=mongodb-1"
    -e "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
    -e "ME_CONFIG_MONGODB_ADMINPASSWORD=test"
    {{docker_mongo_express_image_name}}