---
- name: Instalando o ClamAv
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - clamav 
    - clamav-docs
    - clamav-daemon
    - clamav-freshclam

- name: Instalando verificadores de ficheiros compactados
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - arj
    - arc
    - bzip2
    - cabextract
    - lzop
    - nomarch
    - p7zip-full
    - pax
    - tnef
    - unrar-free
    - unzip
    - zoo
- name: Parando o serviço clamav-freshclam
  service:
    name: clamav-freshclam
    state: stopped
- name: Atualizando a base de dados de assinaturas de vírus
  command: freshclam
  ignore_errors: yes
- name: Iniciando o serviço clamav-freshclam
  service:
    name: clamav-freshclam
    state: started
- name: Reiniciando o daemon clamav-daemon
  service:
    name: clamav-daemon
    state: restarted
  
