- name: instalando pacotes extras para o ansible
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python-pexpect
- name: create a new user
  user: 
    name=rodrigo
    state=present
    groups="sudo"    
    comment=""
- name: Add public ssh key to user
  authorized_key:
    user: rodrigo
    state: present
    key: "{{ lookup('file', 'files/ssh/id_rsa.pub') }}"
