- name: cria a network stack
  docker_network:
    name: stack
    driver: bridge
    
- name: cria o volume elasticsearchdata
  docker_volume:
    name: elasticsearchdata
    driver: local
    
- name: cria o volume kibanaconfig
  docker_volume:
    name: kibanaconfig
    driver: local    
    
- name: cria o container do elasticsearch
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    restart: yes
    env:
      cluster.name: "log-cluster"
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    purge_networks: yes
    networks_cli_compatible: yes
    networks:
      - name: "stack"
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    ports:
     - "9200:9200"

- name: cria o container fluentd
  docker_image:
    name: fluentd
    build:
      path: ./fluentd
    push: yes
    source: build
