---

- name: instalando os pacotes necessários para o apt trabalhar com repositórios sobre HTTPS 
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https 
    - ca-certificates
    - gnupg2
    - software-properties-common
  tags:
    - docker-ce
    
- name: adicionando apt signing key do repositório oficial do docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags:
    - docker-ce
    
- name: adicionando repositório oficial do docker para Debian Stretch
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
  tags:
    - docker-ce
    
- name: indexando o novo repositório com o cache
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes
  tags:
    - docker-ce
    
- name: atualizando a instalação do docker-ce
  apt:
    name: "docker-ce"
    state: latest
  tags:
    - docker-ce
    
- name: Ensure docker-compose is installed and available
  shell: curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
