---
- name: Ingressando no domínio
  win_domain_membership:
    dns_domain_name: RTHOMAZ.LOCAL
    hostname: debian9-vm1
    domain_admin_user: rodrigo@rthomaz.local
    domain_admin_password: password@123
    domain_ou_path: "DC=rthomaz,DC=local"
    state: domain
  register: domain_state

- name: Reiniciando...
  win_reboot:
    when: domain_state.reboot_required
