---
# tasks file for ansible-codes
- name: "Hosts"
  hosts: [servers]
  become: true
  vars:
    ntp_servers: 
      - {cname: 'pdc-server.rthomaz.local', prefer: true }
      - {cname: 'bdc-server.rthomaz.local', prefer: false }
  tasks:
  - include: apt-sources-list.yml
    tags: apt-sources-list
  - include: ntp.yml
    tags: ntp
  - include: clamav.yml
    tags: clamav
