---
# tasks file for ansible-codes
- name: "Hosts"
  hosts: [servers]
  become: true
  vars:
    debian_codename: 'stretch'
    timezone: 'America/Sao_Paulo'
    domain_name: 'RTHOMAZ.LOCAL'
    admin_name : 'rodrigo'
    domain_admin_user : 'rodrigo'
    domain_admin_password : 'b3b3xu!@#'
    ntp_servers: 
      - {cname: 'pdc-server.rthomaz.local', prefer: 'prefer' }
#      - {cname: 'bdc-server.rthomaz.local', prefer: '' }    
  tasks:
  - include: apt-sources-list.yml
    tags: apt-sources-list
  - include: default-packages.yml
    tags: default-packages
  - include: ntpdate.yml
    tags: ntpdate
  - include: ntp.yml
    tags: ntp    
#  - include: clamav.yml
#    tags: clamav
  - include: krb5-user.yml
    tags: krb5-user
  - include: samba-domain-member.yml
    tags: samba-domain-member        
  #- include: join-domain.yml
  #  tags: join-domain
