---
# tasks file for ansible-codes
- name: "Hosts"
  hosts: [servers]
  become: true
  vars:
    packages:
    - clamav 
    - clamav-docs
    - clamav-daemon
    - clamav-freshclam
  tasks:
  - include: apt-sources-list.yml
    tags: apt-sources-list
  - include: ntp.yml
    tags: ntp
  - include: clamav.yml
    tags: clamav
