---
# tasks file for ansible-codes
- name: "Hosts"
  hosts: [servers]
  become: true
  vars:
    ntp_servers: 
      'pdc-server.rthomaz.local'
      'bdc-server.rthomaz.local'
  tasks:
  - include: apt-sources-list.yml
    tags: apt-sources-list
  - include: ntp.yml
    tags: ntp
  - include: clamav.yml
    tags: clamav
