---
# tasks file for ansible-codes
- name: "Hosts"
  hosts: [servers]
  become: true
  vars:
    teste1: 1
    teste2: 5
  tasks:
  - include: apt-sources-list.yml
    tags: apt-sources-list
  - include: ntp.yml
    tags: ntp
  - include: clamav.yml
    tags: clamav
