---
# tasks file for ansible-codes
- name: "Hosts"
  hosts: [servers]
  become: true
  vars:
    debian_codename: 'stretch'
    timezone: 'America/Sao_Paulo'
    ntp_servers: 
      - {cname: 'pdc-server.rthomaz.local', prefer: 'prefer' }
#      - {cname: 'bdc-server.rthomaz.local', prefer: '' }    
  tasks:
  - include: apt-sources-list.yml
    tags: apt-sources-list
  - include: ntp.yml
    tags: ntp
  - include: clamav.yml
    tags: clamav
