- name: Ensure NFS common is installed.
  apt: 
    name=nfs-common
- name: Create mountable dir
  file: path=/mnt/rthomaz state=directory mode=777 owner=root group=root
- name: set mountpoints
  mount: 
    path=/mnt/rthomaz
    src=192.168.1.108:/rthomaz
    fstype=nfs
    state=present
