---
- name: instalando o samba
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - samba
    - winbind
    - smbclient
    - ldap-utils
    - libpam-krb5
    - libnss-winbind
    - libpam-winbind
- name: parando o smbd
  service:
    name: smbd
    state: stopped
- name: parando o nmbd
  service:
    name: nmbd
    state: stopped
- name: parando o winbind
  service:
    name: winbind
    state: stopped
- name: criando ficheiro smb.conf
  template:
    src: "smb.conf.j2"
    dest: "/etc/samba/smb.conf"
    backup: yes
- name: criando ficheiro nsswitch.conf
  copy:
    src: "nsswitch.conf.j2"
    dest: "/etc/nsswitch.conf"
    backup: yes     
- name: ingressando no domínio
  expect:
    command: net ads join -U {{ domain_admin_user }}
    responses:
      (?i)password: '{{ domain_admin_password }}'
  # you don't want to show passwords in your logs
  no_log: true
- name: adicionando winbind na configuração passwd do ficheiro nsswitch.conf
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^passwd:(.*)$' 
    line: 'passwd:         compat winbind'
    backrefs: yes  
- name: adicionando winbind na configuração group do ficheiro nsswitch.conf
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^group:(.*)$' 
    line: 'group:          compat winbind'
    backrefs: yes      
- name: habilitando e iniciando o winbind
  service:
    name: winbind
    state: started
    enabled: yes
- name: iniciando o smbd
  service:
    name: smbd
    state: started
- name: iniciando o nmbd
  service:
    name: nmbd
    state: started
