- name: adiciona o usuário {{ sudo_user }} no grupo sudo
  command: usermod -aG sudo "{{ sudo_user }}"
- name: copiando a chave ssh
  copy:
    src: "/home/rodrigo/.ssh/id_rsa.pub"
    dest: "/home/rodrigo/.ssh/id_rsa.pub"
    backup: yes     
