- name: adiciona o usuário {{ sudo_user }} no grupo sudo
  command: usermod -aG sudo "{{ sudo_user }}"
- name: criando ficheiro /etc/sudoers
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers"
    backup: yes  
