---
- name: instalando o tftpd
  apt:
    name: "tftpd"
- name: adicionando regras em /{{ workgroup_name }}/ufw-rules.sh para tftpd
  lineinfile:
    dest: /{{ workgroup_name }}/ufw-rules.sh
    insertbefore: .*EndMyRules 
    line: |
      # open ports for tftpd
      ufw allow from 192.168.1.0/24 to any port 69 proto udp
- name: rodando o script /{{ workgroup_name }}/ufw-rules.sh
  expect:
    command: /bin/bash -c '/{{ workgroup_name }}/ufw-rules.sh'
    responses:
      (?i)Proceed with operation (y|n)?: "y"
