- name: instalando o ufw
  apt:
    name: 'ufw'
- name: cria o diretório /{{ workgroup_name }} se ele não existir
  file:
    path: /{{ workgroup_name }}
    state: directory
    owner: root
    group: root
    mode: '0777'
#    mode: '1777'
- name: criando ficheiro /{{ workgroup_name }}/ufw-rules.sh
  template:
    src: "ufw-rules.sh.j2"
    dest: "/{{ workgroup_name }}/ufw-rules.sh"
    backup: yes
    mode: a+x
    owner: root
#- name: reiniciando a máquina
#  reboot:
- name: reinicia o sistema se requerido
  command: shutdown -r now 'Rebooting to complete system upgrade'
            removes=/var/run/reboot-required
- name: rodando o script /{{ workgroup_name }}/ufw-rules.sh  
  expect:
    command: /bin/bash -c '/{{ workgroup_name }}/ufw-rules.sh'
    responses:
      (?i)Proceed with operation (y|n)?: "y"
