# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "debian/stretch64"
  config.vm.hostname = "deb-01"  
  config.vm.network :public_network, :dev => "br0", :mode => "bridge", :type => "bridge", ip: "192.168.1.185", :netmask => "255.255.255.0"
  config.vm.synced_folder '.', '/vagrant', disabled: true
# config.vm.synced_folder "PATH_DOT_SSH", "/home/vagrant/.ssh"
 
  config.ssh.insert_key = false
  #config.ssh.host = 'deb-01'
  
  #config.ssh.username = "root"
  #config.ssh.private_key_path = "~/.ssh/id_rsa"
  
  config.vm.provider :libvirt do |provider|
    provider.memory = 512
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "main.yml"
    ansible.inventory_path = "hosts"
    ansible.limit = "192.168.1.185"
  end
  
end
