---

- name: verificar arquivo {{vagrant_file_name}} 
  stat: 
    path: '{{directory_downloads}}/{{vagrant_file_name}}'
    get_checksum: yes
    checksum_algorithm: sha256
  register: vagrant_file

- name: se existir e checksum não conferir, excluir arquivo
  file:
    path: '{{directory_downloads}}/{{vagrant_file_name}}'
    state: absent
  when: vagrant_file.stat.exists == True and vagrant_file.stat.checksum != {{vagrant_checksum}}

- name: download vagrant {{vagrant_version}}
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{vagrant_version}}/{{vagrant_file_name}}
    dest: '{{directory_downloads}}'
    checksum: '{{vagrant_checksum}}'
    owner: root
    group: root
    mode: +rwx
  when: vagrant_file.stat.exists == False or ( vagrant_file.stat.exists == True and vagrant_file.stat.checksum != {{vagrant_checksum}} )