---

- name: download vagrant {{vagrant_version}}
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_x86_64.deb
    dest: '{{directory_downloads}}'
    owner: root
    group: root
    mode: +rwx  