---

- name: download vagrant {{vagrant_version}}
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{vagrant_version}}/{{vagrant_file_name}}
    dest: '{{directory_downloads}}'
    checksum: '{{vagrant_checksum}}'
    owner: root
    group: root
    mode: +rwx  