---

# things

- name: criar {{item}}.things
  copy:
    src: "things/{{item}}.things"
    dest: "/etc/openhab2/things/{{item}}.things"
    backup: no
    owner: root
    group: root
    mode: 0664
  loop:
    - chromecast
    - dht22
    - motion

# items    