---

- name: exclui o container do postgres adminer
  command: docker rm -f -v postgres-adminer-1
  ignore_errors: yes    
    
- name: cria o container do postgres adminer
  command: docker run 
    --restart=unless-stopped -d 
    --name postgres-adminer-1
    --network {{docker_postgres_adminer_network}}
    --log-driver={{docker_postgres_adminer_log_driver}}
    --log-opt fluentd-address={{docker_postgres_adminer_log_address}}
    --log-opt tag={{docker_postgres_adminer_log_tag}}
    -p 8091:8080 
    adminer
