---

- name: instalar bind9
  apt:
    name: "bind9"

- name: para o serviço
  service:
    name: bind9
    state: stopped

- name: criar ficheiro /etc/bind/named.conf
  copy:
    src: "bind.named.conf"
    dest: "/etc/bind/named.conf"
    backup: yes

- name: criar ficheiro /var/lib/samba/private/named.conf
  copy:
    src: "private.named.conf"
    dest: "/var/lib/samba/private/named.conf"
    backup: yes    