---
  
- name: atualizar pacotes apt
  apt:
    update_cache: yes  

- include_role: 
    name: ntp-update

- include_role:
    name: ntp-server

- name: krb5-user
  include_tasks: krb5-user.yml

- name: samba
  include_tasks: samba.yml

- name: ntp-server-config
  include_tasks: ntp-server-config.yml

- name: dhcp-server
  include_tasks: dhcp-server.yml