---

# parando serviços se existirem

- name: verificar se o serviço smbd existe
  stat: path=/etc/init.d/smbd
  register: service_smbd_status

- name: parar serviço smbd
  service:
    name: smbd
    state: stopped
  when: service_smbd_status.stat.exists

- name: verificar se o serviço nmbd existe
  stat: path=/etc/init.d/nmbd
  register: service_nmbd_status

- name: parar serviço nmbd
  service:
    name: nmbd
    state: stopped
  when: service_nmbd_status.stat.exists

- name: verificar se o serviço winbind existe
  stat: path=/etc/init.d/winbind
  register: service_winbind_status    

- name: parar serviço winbind
  service:
    name: winbind
    state: stopped
  when: service_winbind_status.stat.exists

# removendo os arquivos de bando de dados se existirem

# instalando dependências de pacote necessárias 

- name: instalar dependências de pacote necessárias 
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - acl
    - attr
    - autoconf
    - bind9utils
    - bison
    - build-essential
    - debhelper
    - dnsutils
    - docbook-xml
    - docbook-xsl
    - flex
    - gdb
    - libjansson-dev
    - libacl1-dev
    - libaio-dev
    - libarchive-dev
    - libattr1-dev
    - libblkid-dev
    - libbsd-dev
    - libcap-dev
    - libcups2-dev
    - libgnutls28-dev
    - libgpgme-dev
    - libjson-perl
    - libldap2-dev
    - libncurses5-dev
    - libpam0g-dev
    - libparse-yapp-perl
    - libpopt-dev
    - libreadline-dev
    - nettle-dev
    - perl
    - perl-modules
    - pkg-config
    - python-all-dev
    - python-crypto
    - python-dbg
    - python-dev
    - python-dnspython
    - python3-dnspython
    - python-gpgme
    - python3-gpgme
    - python-markdown
    - python3-markdown
    - python3-dev
    - xsltproc
    - zlib1g-dev
    - liblmdb-dev
    - lmdb-utils

# instalando o samba

# provisionando o samba dc

# configurando kerberos

# configurando back-end do dns do dc

# configurando rotas

# configurando rede

# configurando zona reversa

