---
docker_mysql_network: '{{docker_network}}'

docker_mysql_image_name: 'mysql'
docker_mysql_image_release: '5.7.24'

docker_mysql_log_driver: '{{docker_log_driver}}'
docker_mysql_log_address: '{{docker_log_address}}'
docker_mysql_log_tag: 'efk.mysql'

