---

- name: criar diretório {{ docker_work_path }}/influxdb se ele não existir
  file:
    path: '{{ docker_work_path }}/influxdb'
    state: directory
    owner: root
    group: root
    mode: +rwx        

- name: criar Dockerfile {{ docker_work_path }}/influxdb/Dockerfile
  copy:
    src: "Dockerfile"
    dest: "{{ docker_work_path }}/influxdb/Dockerfile"
    backup: no
    mode: a+x
    owner: root
    group: root

- name: build imagem influxdb
  docker_image:
    name: influxdb/debian
    path: "{{ docker_work_path }}/influxdb/"
    tag: latest