---

- name: criar diret처rio {{directory_scripts}} se ele n찾o existir
  file:
    path: '{{directory_scripts}}'
    state: directory
    owner: root
    group: root
    mode: +rwx

- name: criar diret처rio {{directory_downloads}} se ele n찾o existir
  file:
    path: '{{directory_downloads}}'
    state: directory
    owner: root
    group: root
    mode: +rwx    