---

samba_domain_controller_dns_forwarders_current: '{{ samba_domain_controller_dns_forwarders | default(samba_domain_controller_dns_forwarders_default) }}'

reverse_zone: "{{ network_interfaces_address.split('.') [2] + '.' + network_interfaces_address.split('.') [1] + '.' + network_interfaces_address.split('.') [0] + '.in-addr.arpa' }}"