---

- name: cria volume do mongodb-data
  docker_volume:
    name: mongodb-data    
    
- name: exclui qualquer container baseado na imagem {{docker_mongodb_image_name}} 
  shell: docker ps -a | awk '{ print $1,$2 }' | grep {{docker_mongodb_image_name}} | awk '{print $1 }' | xargs -I {} docker rm -f {}
    
- name: cria container {{docker_mongodb_container_name}} 
  command: docker run 
    --restart=unless-stopped -d 
    --name {{docker_mongodb_container_name}} 
    --network {{docker_mongodb_network}}
    --log-driver={{docker_mongodb_log_driver}}
    --log-opt fluentd-address={{docker_mongodb_log_address}}
    --log-opt tag={{docker_mongodb_log_tag}}
    -p 27017:27017 
    -e "MONGO_INITDB_ROOT_USERNAME=root"
    -e "MONGO_INITDB_ROOT_PASSWORD=test"
    {{docker_mongodb_image_name}} 