- name: instalar ufw
  apt:
    name: 'ufw'
  register: instalar_ufw
- name: aguardar o reboot
  wait_for_connection:
    timeout: 900
  when: instalar_ufw.changed    
- name: criar ficheiro {{directory_scripts}}/ufw-rules.sh
  template:
    src: "ufw-rules.sh.j2"
    dest: '{{directory_scripts}}/ufw-rules.sh'
    backup: yes
    mode: a+x
    owner: root
    group: root
  register: criar_ficheiro_ufw_rules
- name: rodando o script {{directory_scripts}}/ufw-rules.sh  
  expect:
    command: /bin/bash -c '{{directory_scripts}}/ufw-rules.sh'
    responses:
      (?i)Proceed with operation (y|n)?: "y"
  when: criar_ficheiro_ufw_rules.changed
