---

- name: criar o diretório {{docker_work_path}} se ele não existir
  file:
    path: '{{docker_work_path}}'
    state: directory
    owner: root
    group: root
    mode: +rwx    
    
- name: criar o diretório {{docker_folder_images_path}} se ele não existir
  file:
    path: '{{docker_folder_images_path}}'
    state: directory
    owner: root
    group: root
    mode: +rwx

- name: criar o diretório {{docker_folder_volumes_path}} se ele não existir
  file:
    path: '{{docker_folder_volumes_path}}'
    state: directory
    owner: root
    group: root
    mode: +rwx

- name: criar os diretórios dos containers se eles não existirem
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: +rwx   
  loop: '{{ docker_folder_volumes_containers_path }}' 

- name: criar a network rthomaz-network
  docker_network:
    name: rthomaz-network
    internal: false
