---

- name: cria o diret처rio {{ docker_work_path }} se ele n찾o existir
  file:
    path: {{ docker_work_path }}
    state: directory
    owner: root
    group: root
    mode: +rwx    
    
- name: cria o diret처rio {{docker_folder_images_path}} se ele n찾o existir
  file:
    path: '{{docker_folder_images_path}}'
    state: directory
    owner: root
    group: root
    mode: +rwx

- name: cria a network rthomaz-network
  docker_network:
    name: rthomaz-network
    internal: false
