---
    
- name: cria o volume do nextcloud
  docker_volume:
    name: nextcloud-data    
    
- name: exclui o container do nextcloud
  command: docker rm -f -v nextcloud-1
  ignore_errors: yes    
    
- name: cria o container do nextcloud
  command: docker run 
    --restart=unless-stopped -d 
    --name nextcloud-1
    --mount source=nextcloud-data,target=/var/www/html
    --network {{docker_nextcloud_network}}
    --log-driver={{docker_nextcloud_log_driver}}
    --log-opt fluentd-address={{docker_nextcloud_log_address}}
    --log-opt tag={{docker_nextcloud_log_tag}}
    -p 8088:80 
    -e "MYSQL_DATABASE=nextcloud"
    -e "MYSQL_USER=nextcloud"
    -e "MYSQL_PASSWORD=changeme"
    -e "MYSQL_HOST=mariadb-1"
    -e "NEXTCLOUD_ADMIN_USER=root"
    -e "NEXTCLOUD_ADMIN_PASSWORD=changeme"
    -e "NEXTCLOUD_DATA_DIR=/var/www/html/data"
    -e "EXTERNAL_URL=192.168.1.185:8088"
    -e "NEXTCLOUD_TRUSTED_DOMAINS=nextcloud-1 localhost mariadb-1 192.168.1.185:8088 rthomaz.local 127.0.0.1"
    nextcloud