---
    
- name: cria o volume do nextcloud-data    
  docker_volume:
    name: nextcloud-data    
    
- name: exclui qualquer container baseado na imagem {{docker_nextcloud_image_name}} 
  shell: docker ps -a | awk '{ print $1,$2 }' | grep {{docker_nextcloud_image_name}} | awk '{print $1 }' | xargs -I {} docker rm -f {}
    
- name: cria container {{docker_nextcloud_container_name}}
  command: docker run 
    --restart=unless-stopped -d 
    --name {{docker_nextcloud_container_name}}
    --mount source=nextcloud-data,target=/var/www/html
    --network {{docker_nextcloud_network}}
    --log-driver={{docker_nextcloud_log_driver}}
    --log-opt fluentd-address={{docker_nextcloud_log_address}}
    --log-opt tag={{docker_nextcloud_log_tag}}
    -p {{docker_nextcloud_port}}:80 
    -e "MYSQL_DATABASE=nextcloud"
    -e "MYSQL_USER=nextcloud"
    -e "MYSQL_PASSWORD=changeme"
    -e "MYSQL_HOST=mariadb-1"
    -e "NEXTCLOUD_ADMIN_USER=root"
    -e "NEXTCLOUD_ADMIN_PASSWORD=changeme"
    -e "NEXTCLOUD_DATA_DIR=/var/www/html/data"
    -e "EXTERNAL_URL=192.168.1.185:8088"
    -e "NEXTCLOUD_TRUSTED_DOMAINS=nextcloud-1 localhost mariadb-1 192.168.1.185:8088 rthomaz.local 127.0.0.1"
    {{docker_nextcloud_image_name}}