---
    
- name: cria o volume do nextcloud-data    
  docker_volume:
    name: nextcloud-data    
    
- name: exclui qualquer container baseado na imagem {{docker_nextcloud_image_name}} 
  shell: docker ps -a | awk '{ print $1,$2 }' | grep {{docker_nextcloud_image_name}} | awk '{print $1 }' | xargs -I {} docker rm -f {}
    
- name: cria container {{docker_nextcloud_container_name}}
  command: docker run 
    --restart=unless-stopped -d 
    --name {{docker_nextcloud_container_name}}
    --mount source=nextcloud-data,target=/var/www/html
    --network {{docker_nextcloud_network}}
    --log-driver={{docker_nextcloud_log_driver}}
    --log-opt fluentd-address={{docker_nextcloud_log_address}}
    --log-opt tag={{docker_nextcloud_log_tag}}
    -p {{docker_nextcloud_port}}:80
    -e "MYSQL_DATABASE={{docker_nextcloud_mysql_database}}"
    -e "MYSQL_USER={{docker_nextcloud_mysql_user}}"
    -e "MYSQL_PASSWORD={{docker_nextcloud_mysql_pass}}"
    -e "MYSQL_HOST={{docker_nextcloud_mysql_host}}"
    -e "NEXTCLOUD_ADMIN_USER={{docker_nextcloud_admin_user}}"
    -e "NEXTCLOUD_ADMIN_PASSWORD={{docker_nextcloud_admin_pass}}"
    -e "NEXTCLOUD_DATA_DIR={{docker_nextcloud_admin_data_dir}}"
    -e "EXTERNAL_URL=192.168.1.185:8088"
    -e "NEXTCLOUD_TRUSTED_DOMAINS=nextcloud-1 localhost mariadb-1 192.168.1.185:8088 rthomaz.local 127.0.0.1"
    {{docker_nextcloud_image_name}}