---
docker_rabbitmq_network: '{{docker_network}}'

docker_rabbitmq_files_owner: '{{docker_files_owner}}'
docker_rabbitmq_files_group: '{{docker_files_group}}'
docker_rabbitmq_files_mode: '{{docker_files_mode}}'

docker_rabbitmq_default_user: '{{docker_apps_default_user}}'
docker_rabbitmq_default_pass: '{{docker_apps_default_pass}}'

docker_rabbitmq_image_name: 'rabbitmq'

docker_rabbitmq_directory_path: '{{docker_work_path}}/{{docker_rabbitmq_directory_name}}'
  
docker_rabbitmq_log_driver: '{{docker_log_driver}}'
docker_rabbitmq_log_address: '{{docker_log_address}}'
docker_rabbitmq_log_tag: 'efk.rabbitmq'