---

- name: cria o diretório {{docker_jenkins_directory_path}} se ele não existir
  file:
    path: '{{docker_jenkins_directory_path}}'
    state: directory
    owner: '{{docker_jenkins_files_owner}}'
    group: '{{docker_jenkins_files_group}}'
    mode: '{{docker_jenkins_files_mode}}'
    
- name: cria {{docker_jenkins_directory_path}}/Dockerfile
  template:
    src: 'Dockerfile'
    dest: '{{docker_jenkins_directory_path}}/Dockerfile'
    backup: yes    
    owner: '{{docker_jenkins_files_owner}}'
    group: '{{docker_jenkins_files_group}}'
    mode: '{{docker_jenkins_files_mode}}'
    
- name: criar imagem rthomaz/jenkins:{{docker_jenkins_release}}
  docker_image:
    name: 'rthomaz/jenkins:{{docker_jenkins_release}}'
    build:
      path: '{{docker_folder_images_path}}'
      dockerfile: '{{docker_jenkins_directory_path}}/Dockerfile'
      pull: yes
    push: no
    source: build
