---

influxdb_url: 'http://192.168.1.5:8086'
influxdb_user: 'openhab'
influxdb_password: 'openhab'
influxdb_db: 'openhab'

home: { 
  name: 'casa', title: 'Casa', icon: 'house', tag: 'Building',
  floors: [
    {
      name: 'piso_terreo', title: 'Piso térreo', icon: 'groundfloor', tag: 'GroundFloor', order: 0,
      rooms: [
        { name: 'quarto', title: 'Quarto', icon: 'bedroom', tag: 'Bedroom', order: 0 },
        { name: 'sala', title: 'Sala', icon: 'sofa', tag: 'LivingRoom', order: 1 },
        { name: 'corredor', title: 'Corredor', icon: 'corridor', tag: 'Corridor', order: 2 },
        { name: 'banheiro', title: 'Banheiro', icon: 'bath', tag: 'Bathroom', order: 3 },
        { name: 'cozinha', title: 'Cozinha', icon: 'kitchen', tag: 'Kitchen', order: 4 },
        { name: 'escritorio', title: 'Escritório', icon: 'office', tag: 'Room', order: 5 }          
      ]
    },
    {
      name: 'lado_de_fora', title: 'Lado de fora', icon: 'garden', tag: 'Outdoor', order: 1,
      rooms: [
        { name: 'quintal', title: 'Quintal', icon: 'lawnmower', tag: 'Garden', order: 0 },
        { name: 'lavanderia', title: 'Lavanderia', icon: 'washingmachine', tag: 'Room', order: 1 },
        { name: 'garagem', title: 'Garagem', icon: 'garage', tag: 'Garage', order: 2 }
      ]
    }
  ] 
}
  

chromecast:
  callbackUrl: 'http://192.168.1.25:8080'
  devices:
    - { type: 'audiogroup', ipAddress: '192.168.1.21', port: 42006, order: 0, room: 'casa', title: 'Grupo Casa', prefix: 'do' }
    - { type: 'audiogroup', ipAddress: '192.168.1.12', port: 57896, order: 1, room: 'grupoNorte', title: 'Grupo Norte', prefix: 'do' }
    - { type: 'audiogroup', ipAddress: '192.168.1.21', port: 42532, order: 2, room: 'grupoSul', title: 'Grupo Sul', prefix: 'do' }  
    - { type: 'chromecast', ipAddress: '192.168.1.15', port: 8009,  order: 3, room: 'quarto', title: 'Quarto', prefix: 'do' }
    - { type: 'chromecast', ipAddress: '192.168.1.12', port: 8009,  order: 4, room: 'sala', title: 'Sala', prefix: 'da' }  
    - { type: 'audio',      ipAddress: '192.168.1.21', port: 8009,  order: 5, room: 'banheiro', title: 'Banheiro', prefix: 'do' }
    - { type: 'assistant',  ipAddress: '192.168.1.25', port: 8009,  order: 6, room: 'cozinha', title: 'Cozinha', prefix: 'da' }
    - { type: 'chromecast', ipAddress: '192.168.1.11', port: 8009,  order: 7, room: 'cozinha', title: 'Cozinha', prefix: 'da' }
    - { type: 'chromecast', ipAddress: '192.168.1.19', port: 8009,  order: 8, room: 'escritorio', title: 'Escritório', prefix: 'do' }

mqqtBroker: 
  host: '192.168.1.5'
  secure: 'false'
  username: 'rodrigo'
  password: '12345'

dhtSensor:
  mqqtBroker: 
    host: '{{ mqqtBroker.host }}'
    secure: '{{ mqqtBroker.secure }}'
    username: '{{ mqqtBroker.username }}'
    password: '{{ mqqtBroker.password }}'
  devices:  
    - { order: 0, room: 'quarto', title: 'Quarto', prefix: 'do' }
    - { order: 1, room: 'sala', title: 'Sala', prefix: 'da' }  
    - { order: 2, room: 'banheiro', title: 'Banheiro', prefix: 'do' }
    - { order: 3, room: 'cozinha', title: 'Cozinha', prefix: 'da' }
    - { order: 4, room: 'escritorio', title: 'Escritório', prefix: 'do' }

pirSensor:
  mqqtBroker: 
    host: '{{ mqqtBroker.host }}'
    secure: '{{ mqqtBroker.secure }}'
    username: '{{ mqqtBroker.username }}'
    password: '{{ mqqtBroker.password }}'
  devices:  
    - { order: 0, room: 'quarto', title: 'Quarto', prefix: 'do' }
    - { order: 1, room: 'sala', title: 'Sala', prefix: 'da' }  
    - { order: 2, room: 'banheiro', title: 'Banheiro', prefix: 'do' }
    - { order: 3, room: 'corredor', title: 'Corredor', prefix: 'do' }
    - { order: 4, room: 'cozinha', title: 'Cozinha', prefix: 'da' }
    - { order: 5, room: 'escritorio', title: 'Escritório', prefix: 'do' }    

thermostat:
  mqqtBroker: 
    host: '{{ mqqtBroker.host }}'
    secure: '{{ mqqtBroker.secure }}'
    username: '{{ mqqtBroker.username }}'
    password: '{{ mqqtBroker.password }}'
  devices:  
    - { order: 0, room: 'quarto', title: 'Quarto', prefix: 'do', inGroup: true }
    - { order: 1, room: 'sala', title: 'Sala', prefix: 'da', inGroup: true }  
    - { order: 2, room: 'banheiro', title: 'Banheiro', prefix: 'do', inGroup: false }
    - { order: 3, room: 'cozinha', title: 'Cozinha', prefix: 'da', inGroup: false }
    - { order: 4, room: 'escritorio', title: 'Escritório', prefix: 'do', inGroup: true }    