---
docker_nuget_server_network: '{{docker_network}}'

docker_nuget_server_image_name: 'sunside/simple-nuget-server'

docker_nuget_server_port: 500

docker_nuget_server_log_driver: '{{docker_log_driver}}'
docker_nuget_server_log_address: '{{docker_log_address}}'
docker_nuget_server_log_tag: 'efk.nuget.server'

