---

- name: instalar krb5-user
  apt:
    name: "krb5-user"    

- name: criar ficheiro krb5.conf
  template:
    src: "krb5.conf.j2"
    dest: "/etc/krb5.conf"
    backup: yes

- name: adicionar regras no firewall
  lineinfile:
    dest: {{directory_scripts}}/ufw-rules.sh
    insertbefore: .*EndMyRules 
    line: |
      # open ports for Kerberos
      ufw allow from {{network_interfaces_prefix}} to any port 88
      ufw allow from {{network_interfaces_prefix}} to any port 464

- name: rodar script {{directory_scripts}}/ufw-rules.sh
  expect:
    command: /bin/bash -c '{{directory_scripts}}/ufw-rules.sh'
    responses:
      (?i)Proceed with operation (y|n)?: "y"      
