---

- name: atualizar pacotes apt
  apt:
    update_cache: yes
  
- include_role: 
    name: ntp-update
  vars:
    ntp_update_server: pdc-server.rthomaz.local

- include_role:
    name: ntp-client

- name: krb5-user
  include_tasks: krb5-user.yml

- name: samba-domain-member
  include_tasks: samba-domain-member.yml

- name: pam
  include_tasks: pam.yml