---

- name: instalar bridge-utils
  apt:
    name: "bridge-utils" 
  when: network_interfaces_mode_bridge_current == 'yes'  

- name: criar ficheiro /etc/default/grub
  copy:
    src: grub
    dest: /etc/default/grub
    backup: yes
  register: criar_ficheiro_grub
  when: network_interfaces_mode_bridge_current == 'yes'  
  
- name: criar novo arquivo grub.cfg
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: network_interfaces_mode_bridge_current == 'yes' and criar_ficheiro_grub.changed

- name: criar ficheiro /etc/network/interfaces
  template:
    src: "interfaces.j2"
    dest: "/etc/network/interfaces"
    backup: yes
  register: criar_ficheiro_interfaces

- name: reiniciar servidor
  reboot:
  when: network_interfaces_mode_bridge_current == 'yes' and ( criar_ficheiro_interfaces.changed or criar_ficheiro_grub.changed )