---

- name: instalar ntp
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ntp
    - ntp-doc

- name: criar ficheiro ntp.conf
  template:
    src: "ntp.conf.j2"
    dest: "/etc/ntp.conf"
    backup: yes
  register: criar_ficheiro_ntp

- name: reiniciar ntp
  service:
    name: ntp
    state: restarted
  when: criar_ficheiro_ntp.changed

- name: adicionar regras no firewall
  lineinfile:
    dest: '{{directory_scripts}}/ufw-rules.sh'
    insertbefore: .*EndMyRules 
    line: |
      # open ports for NTP
      ufw allow from {{interface_network_prefix}} to any port 123 proto udp

- name: executar script {{directory_scripts}}/ufw-rules.sh
  expect:
    command: /bin/bash -c '{{directory_scripts}}/ufw-rules.sh'
    responses:
      (?i)Proceed with operation (y|n)?: "y"      
